


spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jd_user?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Ww571902324
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

thymeleaf:
  prefix: classpath:/templates/

